### ISSUE TITLE
Crash when retrieving from iCloud

### ISSUE THREAD

**Issue by scottfits** [zhangao0086/DKImagePickerController#215]
I love this library but it seems that if you select an older image using Swift 3, it seems to break. The crash is on this line: let image = UIImage(data: data!)

```
`	public func fetchOriginalImage(_ sync: Bool, completeBlock: @escaping (_ image: UIImage?, _ info: [AnyHashable: Any]?) -> Void) {
		let options = PHImageRequestOptions()
		options.version = .current
		options.isSynchronous = sync
		
```
		getImageManager().fetchImageDataForAsset(self, options: options, completeBlock: { (data, info) in
			let image = UIImage(data: data!)
			completeBlock(image, info)
		})
	}`

**Comment by kobinary** [comment]
I found that the issue is happening in 

`	public func fetchImageDataForAsset(_ asset: DKAsset, options: PHImageRequestOptions?, completeBlock: @escaping (_ data: Data?, _ info: [AnyHashable: Any]?) -> Void ...`

when:
 
`if let isInCloud = (info?[PHImageResultIsInCloudKey] as AnyObject).boolValue`
`info?[PHImageResultIsInCloudKey]` is returning a NSString and when trying to do the `.boolValue` get nil and CRASH

**Comment by zhangao0086** [comment]
Thank you all.
I've update the condition with
```swift
if let isInCloud = info?[PHImageResultIsInCloudKey] as AnyObject?
	, image == nil && isInCloud.boolValue && self.autoDownloadWhenAssetIsInCloud {
```

**Comment by kobinary** [comment]
Thanks for that :) waiting for your update

Note: The issue is in both methods: **fetchOriginalImage** and **fetchImageDataForAsset**
