### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by bilawal-liaqat** [zhangao0086/DKImagePickerController#401]
app getting crash on this line 

        getImageManager().groupDataManager.assetGroupTypes = self.assetGroupTypes
in file DKImagePickerController

**Comment by sidshah13** [comment]
i am also face same issue

**Comment by rahulbluemark** [comment]
I am facing the same problem.
If I try to open photos second time the app crashes on the same line of code mentioned by @bilawal-liaqat 
Kindly give a solution to it. This is stopping me to update my app.

**Comment by bilawal-liaqat** [comment]
@rahulbluemark yes I m facing that issue when trying to open the second time.

**Comment by wtj123** [comment]
I also have the same issue.

**Comment by RoamingTails** [comment]
@zhangao0086 request you to provide a solution to this issue. 
Awaiting your response.

**Comment by zhangao0086** [comment]
Hi @RoamingTails Can you reproduce it in my example?

**Comment by akuzminskyi** [comment]
I've found a similar issue #410 from the comment
> I changed libs and was having a similar crash. I realised that my permissions inside the Info.plist file were incorrect. Make sure you have NSCameraUsageDescription and NSPhotoLibraryUsageDescription and it should work.

**Comment by vivektakrani** [comment]
I am facing the same issue, @akuzminskyi I checked, already have those in my info.plist...
Did anyone find any solution?

**Comment by xyxy616161** [comment]
Updating the library fixed this issue.
This issue is related to #324

**Comment by zhangao0086** [comment]
Hi all, this issue was fixed in 4.0.0 branch. I'll release it as soon as I finish the final test.
The 4.0.0 branch contains some new features, like so [DKImageAssetExporter](https://github.com/zhangao0086/DKImagePickerController/blob/Feature/4.0.0/DKImagePickerController/DKImageAssetExporter.swift), [DKImageExtensionController](https://github.com/zhangao0086/DKImagePickerController/blob/Feature/4.0.0/DKImagePickerController/DKImageExtensionController.swift) etc.

**Comment by zhangao0086** [comment]
Closing this thread. Feel free to re-open if your issue is not solved.
