### ISSUE TITLE
allowSwipeToSelect with scroll functinality

### ISSUE THREAD

**Issue by paramu** [zhangao0086/DKImagePickerController#441]
How do we enable scroll functionality, when we enable the allowSwipeToSelect functionality in DKImagePicker?

**Comment by jasonjanofsky** [comment]
Heya, I built that feature and didn’t consider building with scrolling in
mind… Unfortunately, I don’t have the time to work on it right now either.

Thanks,

Jason Janofsky

On February 26, 2018 at 1:05:48 PM, paramu (notifications@github.com) wrote:

How do we enable scroll functionality, when we enable the
allowSwipeToSelect functionality in DKImagePicker?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zhangao0086/DKImagePickerController/issues/441>, or mute
the thread

**Comment by paramu** [comment]
Thanks for your quick response.Can you give the idea to build that feature?

**Comment by jasonjanofsky** [comment]
Tough because the recognizer needs to be on the swipe.. which is also used
for the scroll so maybe some kind of toggle?  Maybe a bit of margin on the
right of the scroll view that would allow scrolling — like a big oversized
scroll bar?

Good luck,

-- 
Jason Janofsky

On February 26, 2018 at 1:12:21 PM, paramu (notifications@github.com) wrote:

Thanks for your quick response.Can you give the idea to build that feature?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zhangao0086/DKImagePickerController/issues/441#issuecomment-368652108>,
or mute the thread

**Comment by paramu** [comment]
Thanks @jasonjanofsky

**Comment by sorianog** [comment]
@zhangao0086 What's the priority on this?

**Comment by zhangao0086** [comment]
@sorianog Done. Check this: https://github.com/zhangao0086/DKImagePickerController/commit/27d88edce2040785ab9f704f5b119797999e83fd

I'll bump version to 4.0.4 today.

**Comment by zhangao0086** [comment]
Closing this thread...
