### ISSUE TITLE
Image orientation changes on capture new images 

### ISSUE THREAD

**Issue by BhaveshKumbhani** [zhangao0086/DKImagePickerController#553]
Capture new photo to  reproduce the issue.
Please check screenshot, which is captured in portrait mode.

![img_0080](https://user-images.githubusercontent.com/769383/48941298-fdcfce80-ef40-11e8-8d3f-fd8111bd6e9d.jpg)

**Comment by Bitcosoftware** [comment]
I have found this issue as well when taking picture from the iPhone.

**Comment by lawicko** [comment]
I think this problem was introduced in [4.1.0](https://github.com/zhangao0086/DKImagePickerController/releases/tag/4.1.0) together with the TOCropViewController. From what I can see, this only happens on iPhone X. All the other iPhones I tested were ok (iPhone XS Max, iPhone 8 Plus, iPhone 6). The funny thing is that this is actually how it _should_ behave, at least according to the TOCropViewController author.

If you are interested of the details, here goes:
In the TOCropViewController.m there is this:
```
if (angle == 0 && CGRectEqualToRect(cropFrame, (CGRect){CGPointZero, self.image.size})) {
   image = self.image;
}
else {
   image = [self.image croppedImageWithFrame:cropFrame angle:angle circularClip:NO];
}
```
this _if_ is true on iPhone X, and false on all other iPhones I tested. From looking at this, I'd assume the _if_ should be true if the user didn't do any cropping or rotations, but somehow this is not the case on all devices except iPhone X. If the original image is returned, it contains the orientation metadata, this is why you see your image rotated. In other cases new image is created without the orientation metadata.

For example, on iPhone 8 Plus, without doing any cropping, I get the following:
`cropFrame = (origin = (x = 0, y = 0), size = (width = 2265, height = 4032))`
`self.image.size = (width = 2269, height = 4032)`
So somehow they are not equal.

Version [4.1.1](https://github.com/zhangao0086/DKImagePickerController/releases/tag/4.1.1) promises, that the cropping functionality can be disabled, but I wasn't able to figure out how to do it, any hints? The `extensionsController` is private, so it doesn't look like it can be manipulated from outside and the default set of extensions is always loaded:
```
private lazy var extensionController: DKImageExtensionController! = {
        return DKImageExtensionController(imagePickerController: self)
    }()
```

**Comment by jasudev** [comment]
I have the same issue. Did you resolve this issue?

**Comment by blyscuit** [comment]
I fix this by using custom camera class which load iOS default camera with the [class in example](https://github.com/zhangao0086/DKImagePickerController/blob/develop/Example/DKImagePickerControllerDemo/CustomCamera/CustomCameraExtension.swift) and call this method when presenting image picker
`DKImageExtensionController.registerExtension(extensionClass: CustomCameraExtension.self, for: .camera)
                        self.present(pickerController, animated: true, completion: nil)`

**Comment by bkennedy** [comment]
I am having this same issue as well on iPhone X and am seeing exactly what lawicko is seeing

**Comment by abdulrehman-kiwi** [comment]
having the same issue. Any solution?

**Comment by BhaveshKumbhani** [comment]
extension UIImage{
    
    func rotateFix() -> UIImage {
        var rotatedImage = UIImage()
        switch self.imageOrientation
        {
        case .right:
            rotatedImage = UIImage(cgImage: self.cgImage!, scale: 1.0, orientation: .down)
            
        case .down:
            rotatedImage = UIImage(cgImage: self.cgImage!, scale: 1.0, orientation: .left)
            
        case .left:
            rotatedImage = UIImage(cgImage: self.cgImage!, scale: 1.0, orientation: .up)
            
        default:
            rotatedImage = UIImage(cgImage: self.cgImage!, scale: 1.0, orientation: .right)
        }
        return rotatedImage
    }
    
    static func bookmarkEnableImage() -> UIImage {
        return UIImage.init(named: "bookmark_enable")!
    }
    
    static func bookmarkDisableImage() -> UIImage {
        return UIImage.init(named: "bookmark_disable")!
    }
}

**Comment by zhangao0086** [comment]
Fixed with:
```swift
let imageCropper = CropViewController(image: sourceImage)
imageCropper.onDidCropToRect = { [weak self] image, _, _ in
    guard let strongSelf = self else { return }
    
    if let didFinishEditing = strongSelf.didFinishEditing {
        if sourceImage != image {
            strongSelf.metadata?[kCGImagePropertyOrientation] = NSNumber(integerLiteral: 1)
        }
                        
        didFinishEditing(image, strongSelf.metadata)
        
        strongSelf.didFinishEditing = nil
        strongSelf.metadata = nil
    }
}
```
